
basic:
  model: base
  vocab_size: 2000
  batch_size: 32
  layers: 2
  heads: 2
  dff: 128
  d_model: 32
  max_pe: 1000
  dropout: 0.1
  epochs: 10
  lr: 0.0001

big_basic:
  model: base
  vocab_size: 2000
  batch_size: 32
  layers: 6
  heads: 8
  dff: 128
  d_model: 32
  max_pe: 1000
  dropout: 0.1
  epochs: 20
  lr: 0.0001
