
basic:
  model: base
  vocab_size: 2000
  batch_size: 32
  layers: 2
  heads: 2
  dff: 128
  d_model: 32
  max_pe: 1000
  dropout: 0.1
  epochs: 10
  warmup_steps: 4000
  lr_scale: 1.0

big_basic:
  model: base
  vocab_size: 2000
  batch_size: 32
  layers: 6
  heads: 8
  dff: 128
  d_model: 32
  max_pe: 1000
  dropout: 0.1
  epochs: 20
  warmup_steps: 4000
  lr_scale: 1.0

aiayn:
  model: base
  vocab_size: 10000
  batch_size: 20
  layers: 6
  heads: 8
  dff: 2048
  d_model: 512
  max_pe: 1500
  dropout: 0.1
  epochs: 15
  warmup_steps: 4000
  lr_scale: 0.1
